export type WidgetThemePayload = {
  id: string;
  type: string;
  vars: Record<string, string>;
};

export const WIDGET_THEME_FALLBACK_VARS = {
  '--color-text-primary': '#e8e8e8',
  '--color-text-secondary': '#b0b0b0',
  '--color-text-muted': '#858585',
  '--color-accent-500': '#60a5fa',
  '--color-accent-600': '#3b82f6',
  '--color-bg-secondary': '#1c1c1f',
  '--color-success': '#34d399',
  '--color-warning': '#f59e0b',
  '--color-error': '#ef4444',
  '--color-static-white': '#ffffff',
  '--border-subtle': 'rgba(255, 255, 255, 0.1)',
  '--border-base': 'rgba(255, 255, 255, 0.16)',
  '--border-medium': 'rgba(255, 255, 255, 0.24)',
  '--element-bg-subtle': 'rgba(255, 255, 255, 0.05)',
  '--element-bg-base': 'rgba(255, 255, 255, 0.08)',
  '--element-bg-medium': 'rgba(255, 255, 255, 0.14)',
  '--element-bg-soft': 'rgba(255, 255, 255, 0.08)',
  '--shadow-xs': '0 1px 2px rgba(0, 0, 0, 0.4)',
  '--shadow-sm': '0 2px 4px rgba(0, 0, 0, 0.4)',
} as const;

export function createWidgetThemeFallbackCss(): string {
  return Object.entries(WIDGET_THEME_FALLBACK_VARS)
    .map(([name, value]) => `      ${name}: ${value};`)
    .join('\n');
}

const THEME_VAR_NAMES = [
  '--color-bg-primary',
  '--color-static-white',
  '--color-static-black',
  '--color-overlay-white-02',
  '--color-overlay-white-03',
  '--color-overlay-white-04',
  '--color-overlay-white-05',
  '--color-overlay-white-06',
  '--color-overlay-white-08',
  '--color-overlay-white-10',
  '--color-overlay-white-12',
  '--color-overlay-white-15',
  '--color-overlay-white-20',
  '--color-overlay-white-60',
  '--color-overlay-black-06',
  '--color-overlay-black-08',
  '--color-overlay-black-10',
  '--color-overlay-black-12',
  '--color-overlay-black-15',
  '--color-overlay-black-20',
  '--color-overlay-black-25',
  '--color-overlay-black-30',
  '--color-overlay-black-40',
  '--color-overlay-black-50',
  '--color-overlay-black-80',
  '--color-bg-secondary',
  '--color-bg-tertiary',
  '--color-bg-quaternary',
  '--color-bg-elevated',
  '--color-bg-workbench',
  '--color-bg-scene',
  '--color-bg-flowchat',
  '--color-bg-surface',
  '--color-bg-base',
  '--color-bg-subtle',
  '--color-bg-hover',
  '--color-bg-elevated-hover',
  '--color-hover',
  '--color-background-secondary',
  '--color-background-tertiary',
  '--background-primary',
  '--background-secondary',
  '--background-tertiary',
  '--bg-primary',
  '--bg-secondary',
  '--bg-tertiary',
  '--bg-elevated',
  '--bg-hover',
  '--secondary-bg',
  '--color-surface-elevated',
  '--color-surface-hover',
  '--color-bg-tooltip',
  '--color-text-primary',
  '--color-text-secondary',
  '--color-text-tertiary',
  '--text-primary',
  '--text-secondary',
  '--text-tertiary',
  '--text-muted',
  '--text-disabled',
  '--color-text-muted',
  '--color-text-disabled',
  '--color-accent-50',
  '--color-accent-100',
  '--color-accent-200',
  '--color-accent-300',
  '--color-accent-400',
  '--color-accent-500',
  '--color-accent-600',
  '--color-accent-700',
  '--color-accent-800',
  '--color-accent',
  '--color-accent-primary',
  '--color-accent-alpha',
  '--color-primary',
  '--color-primary-rgb',
  '--color-primary-400',
  '--color-primary-hover',
  '--color-primary-500',
  '--color-primary-alpha',
  '--color-primary-bg',
  '--color-primary-bg-subtle',
  '--accent-primary',
  '--accent-primary-hover',
  '--color-success',
  '--color-success-bg',
  '--color-success-border',
  '--color-success-100',
  '--color-success-500',
  '--color-warning',
  '--color-warning-bg',
  '--color-warning-border',
  '--color-warning-100',
  '--color-warning-500',
  '--color-warning-700',
  '--color-error',
  '--color-error-bg',
  '--color-error-border',
  '--color-semantic-error',
  '--color-danger',
  '--color-danger-500',
  '--color-danger-text',
  '--color-danger-bg',
  '--color-danger-border',
  '--color-danger-hover',
  '--color-info',
  '--color-info-bg',
  '--color-info-border',
  '--border-subtle',
  '--border-color',
  '--border-base',
  '--border-medium',
  '--border-hover',
  '--border-strong',
  '--border-prominent',
  '--border-muted',
  '--border-primary',
  '--color-border',
  '--color-border-primary',
  '--color-border-subtle',
  '--z-base',
  '--z-decoration',
  '--z-content',
  '--z-header',
  '--z-sticky',
  '--z-bottom-bar',
  '--z-floating',
  '--z-dropdown',
  '--z-overlay',
  '--z-drawer',
  '--z-modal',
  '--z-modal-active',
  '--z-fullscreen',
  '--z-toast',
  '--z-tooltip',
  '--z-popover',
  '--z-notification',
  '--z-context-menu',
  '--z-extreme',
  '--element-bg-subtle',
  '--element-bg-soft',
  '--element-bg-base',
  '--element-bg-medium',
  '--element-bg-strong',
  '--element-bg-elevated',
  '--element-bg',
  '--element-bg-hover',
  '--scrollbar-thumb',
  '--scrollbar-thumb-hover',
  '--color-scrollbar',
  '--glass-base',
  '--glass-bg-base',
  '--glass-bg-hover',
  '--glass-bg-active',
  '--glass-border-base',
  '--glass-border-hover',
  '--glass-border-focus',
  '--glass-blur-sm',
  '--glass-blur-base',
  '--glass-shadow-sm',
  '--glass-shadow-base',
  '--glass-shadow-lg',
  '--glass-shadow-xl',
  '--shadow-xs',
  '--shadow-sm',
  '--shadow-base',
  '--shadow-lg',
  '--shadow-xl',
  '--radius-sm',
  '--radius-base',
  '--radius-md',
  '--radius-lg',
  '--radius-xl',
  '--radius-2xl',
  '--radius-full',
  '--size-radius-sm',
  '--size-radius-base',
  '--size-radius-md',
  '--size-radius-lg',
  '--size-radius-xl',
  '--spacing-1',
  '--spacing-2',
  '--spacing-3',
  '--spacing-4',
  '--spacing-5',
  '--spacing-6',
  '--spacing-8',
  '--spacing-10',
  '--spacing-12',
  '--spacing-16',
  '--size-gap-1',
  '--size-gap-2',
  '--size-gap-3',
  '--size-gap-4',
  '--size-gap-5',
  '--size-gap-6',
  '--size-gap-8',
  '--size-gap-10',
  '--size-gap-12',
  '--size-gap-16',
  '--font-size-xxs',
  '--font-size-2xs',
  '--font-size-xs',
  '--font-size-sm',
  '--font-size-base',
  '--font-size-lg',
  '--font-size-xl',
  '--font-size-2xl',
  '--font-weight-medium',
  '--font-weight-semibold',
  '--opacity-disabled',
  '--opacity-hover',
  '--opacity-focus',
  '--flowchat-font-size-xxs',
  '--flowchat-font-size-2xs',
  '--flowchat-font-size-xs',
  '--flowchat-font-size-sm',
  '--flowchat-font-size-base',
  '--flowchat-font-size-lg',
  '--flowchat-font-size-xl',
  '--flowchat-font-size-2xl',
  '--flowchat-font-size-3xl',
  '--flowchat-font-size-4xl',
  '--flowchat-font-size-5xl',
  '--flowchat-text-line-height',
  '--flowchat-support-line-height',
  '--flowchat-compact-line-height',
  '--flowchat-flow-item-gap',
  '--flowchat-inline-gap',
  '--flowchat-control-gap',
  '--flowchat-control-pad-y',
  '--flowchat-control-pad-x',
  '--flowchat-card-gap',
  '--flowchat-card-radius',
  '--flowchat-card-pad-y',
  '--flowchat-card-pad-x',
  '--flowchat-card-tight-pad-y',
  '--flowchat-card-tight-pad-x',
  '--flowchat-card-header-pad-y',
  '--flowchat-card-header-pad-x',
  '--flowchat-card-header-pad-right',
  '--flowchat-card-expanded-pad-y',
  '--flowchat-card-expanded-pad-x',
  '--flowchat-code-font-size',
  '--flowchat-code-line-height',
  '--flowchat-code-block-pad-y',
  '--flowchat-code-block-pad-x',
  '--flowchat-markdown-block-gap',
  '--flowchat-markdown-paragraph-gap',
  '--flowchat-markdown-list-item-gap',
  '--flowchat-markdown-list-nested-gap',
  '--flowchat-markdown-heading-gap-before',
  '--flowchat-markdown-heading-gap-after',
  '--flowchat-markdown-code-block-gap',
  '--flowchat-markdown-code-block-pad-y',
  '--flowchat-markdown-code-block-pad-x',
  '--flowchat-markdown-table-cell-pad-y',
  '--flowchat-markdown-table-cell-pad-x',
  '--bitfun-nav-row-action-size',
  '--bitfun-nav-row-action-icon-size',
  '--bitfun-nav-row-action-offset',
  '--bitfun-nav-row-action-gap',
  '--motion-fast',
  '--motion-normal',
  '--motion-base',
  '--motion-slow',
  '--smooth-height-collapse-duration',
  '--easing-standard',
  '--font-family-sans',
  '--font-family-mono',
  '--font-sans',
  '--font-mono',
  '--markdown-font-mono',
  '--tool-card-font-mono',
  '--tool-compact-summary-font',
  '--btn-primary-bg',
  '--btn-primary-color',
  '--btn-primary-border',
  '--btn-primary-shadow',
  '--btn-primary-hover-bg',
  '--btn-primary-hover-color',
  '--btn-primary-hover-border',
  '--btn-primary-hover-shadow',
  '--btn-primary-hover-transform',
  '--btn-primary-active-bg',
  '--btn-primary-active-color',
  '--btn-primary-active-border',
  '--btn-primary-active-shadow',
  '--btn-primary-active-transform',
  '--btn-ghost-bg',
  '--btn-ghost-color',
  '--btn-ghost-border',
  '--btn-ghost-shadow',
  '--btn-ghost-hover-bg',
  '--btn-ghost-hover-color',
  '--btn-ghost-hover-border',
  '--btn-ghost-hover-shadow',
  '--btn-ghost-hover-transform',
  '--btn-ghost-active-bg',
  '--btn-ghost-active-color',
  '--btn-ghost-active-border',
  '--btn-ghost-active-shadow',
  '--btn-ghost-active-transform',
  '--tool-card-bg-primary',
  '--tool-card-bg-secondary',
  '--tool-card-bg-hover',
  '--tool-card-bg-elevated',
  '--tool-card-border',
  '--tool-card-border-subtle',
  '--tool-card-text-primary',
  '--tool-card-text-secondary',
  '--tool-card-text-muted',
  '--tool-card-header-pad-y',
  '--tool-card-header-pad-x',
  '--tool-card-header-pad-right',
  '--tool-card-header-icon-rail',
  '--tool-card-header-icon-slot',
  '--tool-card-icon-size',
  '--tool-card-expanded-pad-y',
  '--tool-card-expanded-pad-x',
  '--tool-card-action-font-size',
  '--tool-card-action-line-height',
  '--tool-card-action-font-weight',
] as const;

export function readWidgetThemePayload(): WidgetThemePayload | null {
  if (typeof window === 'undefined' || typeof document === 'undefined') {
    return null;
  }

  const root = document.documentElement;
  const styles = window.getComputedStyle(root);
  const vars: Record<string, string> = {};

  for (const name of THEME_VAR_NAMES) {
    const value = styles.getPropertyValue(name).trim();
    if (value) {
      vars[name] = value;
    } else if (name in WIDGET_THEME_FALLBACK_VARS) {
      vars[name] = WIDGET_THEME_FALLBACK_VARS[name as keyof typeof WIDGET_THEME_FALLBACK_VARS];
    }
  }

  return {
    id: root.getAttribute('data-theme') || 'unknown',
    type: root.getAttribute('data-theme-type') || 'dark',
    vars,
  };
}
