use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use std::process::Command;
use thiserror::Error;

const MEMORY_BASELINE_COMMIT_MESSAGE: &str = "Memory workspace baseline";
const MEMORY_WORKSPACE_DIFF_MAX_BYTES: usize = 200_000;

#[derive(Debug, Error)]
pub enum MemoryWorkspaceGitError {
    #[error("Failed to create memory workspace {root}: {source}")]
    CreateRoot {
        root: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("Failed to inspect memory workspace git metadata {path}: {source}")]
    InspectGitMetadata {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("Failed to remove memory workspace git metadata {path}: {source}")]
    RemoveGitMetadata {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("Failed to read memory workspace directory {path}: {source}")]
    ReadDirectory {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("Failed to read memory workspace directory entry {path}: {source}")]
    ReadDirectoryEntry {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("Failed to inspect memory workspace entry {path}: {source}")]
    InspectEntry {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("Failed to normalize memory workspace path {path} under {root}: {source}")]
    NormalizePath {
        root: PathBuf,
        path: PathBuf,
        #[source]
        source: std::path::StripPrefixError,
    },
    #[error("Failed to read added memory workspace file {path}: {source}")]
    ReadAddedFile {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("Failed to run memory workspace git command in {root}: {source}")]
    RunGit {
        root: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("Memory workspace git command failed in {root}: {stderr}")]
    GitFailed { root: PathBuf, stderr: String },
    #[error("Memory workspace git output was not UTF-8: {source}")]
    GitOutputUtf8 {
        #[source]
        source: std::string::FromUtf8Error,
    },
    #[error("Unsupported memory workspace git status '{status}': {line}")]
    UnsupportedGitStatus { status: char, line: String },
    #[error("Memory workspace git task failed: {source}")]
    Join {
        #[source]
        source: tokio::task::JoinError,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MemoryWorkspaceChangeStatus {
    Added,
    Modified,
    Deleted,
}

impl MemoryWorkspaceChangeStatus {
    pub fn label(self) -> &'static str {
        match self {
            Self::Added => "A",
            Self::Modified => "M",
            Self::Deleted => "D",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MemoryWorkspaceChange {
    pub status: MemoryWorkspaceChangeStatus,
    pub path: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MemoryWorkspaceDiff {
    pub changes: Vec<MemoryWorkspaceChange>,
    pub unified_diff: String,
}

impl MemoryWorkspaceDiff {
    pub fn has_changes(&self) -> bool {
        !self.changes.is_empty()
    }
}

pub async fn ensure_memory_workspace_git_baseline(
    root: &Path,
) -> Result<(), MemoryWorkspaceGitError> {
    let root = root.to_path_buf();
    tokio::task::spawn_blocking(move || {
        create_root(&root)?;

        if root.join(".git").is_dir() && run_git(&root, &["rev-parse", "--verify", "HEAD"]).is_ok()
        {
            return Ok(());
        }

        reset_memory_workspace_git_baseline_sync(&root)
    })
    .await
    .map_err(|source| MemoryWorkspaceGitError::Join { source })?
}

pub async fn reset_memory_workspace_git_baseline(
    root: &Path,
) -> Result<(), MemoryWorkspaceGitError> {
    let root = root.to_path_buf();
    tokio::task::spawn_blocking(move || reset_memory_workspace_git_baseline_sync(&root))
        .await
        .map_err(|source| MemoryWorkspaceGitError::Join { source })?
}

pub async fn memory_workspace_diff(
    root: &Path,
) -> Result<MemoryWorkspaceDiff, MemoryWorkspaceGitError> {
    let root = root.to_path_buf();
    tokio::task::spawn_blocking(move || memory_workspace_diff_sync(&root))
        .await
        .map_err(|source| MemoryWorkspaceGitError::Join { source })?
}

pub fn render_memory_workspace_diff_file(diff: &MemoryWorkspaceDiff) -> String {
    let mut rendered = String::from(
        "# Memory Workspace Diff\n\n\
         Generated by BitFun before Phase 2 memory consolidation. Read this file first and do not edit it.\n\n\
         ## Status\n",
    );

    if !diff.has_changes() {
        rendered.push_str("- none\n");
        return rendered;
    }

    for change in &diff.changes {
        rendered.push_str(&format!("- {} {}\n", change.status.label(), change.path));
    }
    rendered.push_str("\n## Diff\n\n```diff\n");
    append_bounded_diff(&mut rendered, &diff.unified_diff);
    rendered.push_str("```\n");
    rendered
}

fn create_root(root: &Path) -> Result<(), MemoryWorkspaceGitError> {
    std::fs::create_dir_all(root).map_err(|source| MemoryWorkspaceGitError::CreateRoot {
        root: root.to_path_buf(),
        source,
    })
}

fn reset_memory_workspace_git_baseline_sync(root: &Path) -> Result<(), MemoryWorkspaceGitError> {
    create_root(root)?;
    remove_git_metadata(root)?;
    run_git_raw(root, &["init"])?;
    run_git(root, &["add", "-A"])?;
    run_git(
        root,
        &[
            "commit",
            "--allow-empty",
            "-m",
            MEMORY_BASELINE_COMMIT_MESSAGE,
        ],
    )?;
    Ok(())
}

fn remove_git_metadata(root: &Path) -> Result<(), MemoryWorkspaceGitError> {
    let path = root.join(".git");
    let metadata = match std::fs::symlink_metadata(&path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(source) => {
            return Err(MemoryWorkspaceGitError::InspectGitMetadata { path, source });
        }
    };

    let result = if metadata.is_dir() && !metadata.file_type().is_symlink() {
        std::fs::remove_dir_all(&path)
    } else {
        std::fs::remove_file(&path)
    };

    result.map_err(|source| MemoryWorkspaceGitError::RemoveGitMetadata { path, source })
}

fn memory_workspace_diff_sync(root: &Path) -> Result<MemoryWorkspaceDiff, MemoryWorkspaceGitError> {
    run_git(root, &["rev-parse", "--verify", "HEAD"])?;

    let tracked_status = git_stdout(
        root,
        &["diff", "--name-status", "--no-renames", "HEAD", "--"],
    )?;
    let mut changes = parse_git_name_status(&tracked_status)?;
    let head_paths = git_z_stdout(root, &["ls-tree", "-r", "--name-only", "-z", "HEAD"])?;
    let head_paths = parse_nul_paths(&head_paths);
    let current_paths = collect_current_memory_paths(root)?;

    for path in current_paths.difference(&head_paths) {
        changes.push(MemoryWorkspaceChange {
            status: MemoryWorkspaceChangeStatus::Added,
            path: path.clone(),
        });
    }

    changes.sort_by(|left, right| left.path.cmp(&right.path));
    changes.dedup_by(|left, right| left.path == right.path);

    let mut unified_diff = git_stdout(
        root,
        &["diff", "--no-ext-diff", "--no-renames", "HEAD", "--"],
    )?;
    for change in changes
        .iter()
        .filter(|change| change.status == MemoryWorkspaceChangeStatus::Added)
    {
        unified_diff.push_str(&render_added_file_diff(root, &change.path)?);
    }

    Ok(MemoryWorkspaceDiff {
        changes,
        unified_diff,
    })
}

fn collect_current_memory_paths(root: &Path) -> Result<BTreeSet<String>, MemoryWorkspaceGitError> {
    let mut paths = BTreeSet::new();
    collect_current_memory_paths_inner(root, root, &mut paths)?;
    Ok(paths)
}

fn collect_current_memory_paths_inner(
    root: &Path,
    dir: &Path,
    paths: &mut BTreeSet<String>,
) -> Result<(), MemoryWorkspaceGitError> {
    for entry in
        std::fs::read_dir(dir).map_err(|source| MemoryWorkspaceGitError::ReadDirectory {
            path: dir.to_path_buf(),
            source,
        })?
    {
        let entry = entry.map_err(|source| MemoryWorkspaceGitError::ReadDirectoryEntry {
            path: dir.to_path_buf(),
            source,
        })?;
        let path = entry.path();
        if path.file_name().and_then(|name| name.to_str()) == Some(".git") {
            continue;
        }
        let metadata =
            entry
                .metadata()
                .map_err(|source| MemoryWorkspaceGitError::InspectEntry {
                    path: path.clone(),
                    source,
                })?;
        if metadata.is_dir() {
            collect_current_memory_paths_inner(root, &path, paths)?;
        } else if metadata.is_file() {
            paths.insert(relative_memory_path(root, &path)?);
        }
    }
    Ok(())
}

fn relative_memory_path(root: &Path, path: &Path) -> Result<String, MemoryWorkspaceGitError> {
    let relative =
        path.strip_prefix(root)
            .map_err(|source| MemoryWorkspaceGitError::NormalizePath {
                root: root.to_path_buf(),
                path: path.to_path_buf(),
                source,
            })?;
    Ok(relative.to_string_lossy().replace('\\', "/"))
}

fn parse_git_name_status(
    output: &str,
) -> Result<Vec<MemoryWorkspaceChange>, MemoryWorkspaceGitError> {
    let mut changes = Vec::new();
    for line in output.lines().filter(|line| !line.trim().is_empty()) {
        let mut parts = line.splitn(2, char::is_whitespace);
        let status = parts.next().unwrap_or_default();
        let path = parts.next().unwrap_or_default().trim();
        let status = match status.chars().next() {
            Some('A') => MemoryWorkspaceChangeStatus::Added,
            Some('M') => MemoryWorkspaceChangeStatus::Modified,
            Some('D') => MemoryWorkspaceChangeStatus::Deleted,
            Some(status) => {
                return Err(MemoryWorkspaceGitError::UnsupportedGitStatus {
                    status,
                    line: line.to_string(),
                });
            }
            None => continue,
        };
        if !path.is_empty() {
            changes.push(MemoryWorkspaceChange {
                status,
                path: path.replace('\\', "/"),
            });
        }
    }
    Ok(changes)
}

fn parse_nul_paths(output: &[u8]) -> BTreeSet<String> {
    output
        .split(|byte| *byte == 0)
        .filter(|part| !part.is_empty())
        .map(|part| String::from_utf8_lossy(part).replace('\\', "/"))
        .collect()
}

fn render_added_file_diff(root: &Path, path: &str) -> Result<String, MemoryWorkspaceGitError> {
    let file_path = root.join(path);
    let body = std::fs::read_to_string(&file_path).map_err(|source| {
        MemoryWorkspaceGitError::ReadAddedFile {
            path: file_path,
            source,
        }
    })?;
    let diff = similar::TextDiff::from_lines("", &body);
    let mut rendered = format!(
        "diff --git a/{path} b/{path}\nnew file mode 100644\n--- /dev/null\n+++ b/{path}\n"
    );
    for change in diff.iter_all_changes() {
        let sign = match change.tag() {
            similar::ChangeTag::Delete => "-",
            similar::ChangeTag::Insert => "+",
            similar::ChangeTag::Equal => " ",
        };
        rendered.push_str(sign);
        rendered.push_str(change.value());
    }
    if !rendered.ends_with('\n') {
        rendered.push('\n');
    }
    Ok(rendered)
}

fn append_bounded_diff(rendered: &mut String, diff: &str) {
    if diff.len() <= MEMORY_WORKSPACE_DIFF_MAX_BYTES {
        rendered.push_str(diff);
        if !diff.ends_with('\n') {
            rendered.push('\n');
        }
        return;
    }

    let boundary = previous_char_boundary(diff, MEMORY_WORKSPACE_DIFF_MAX_BYTES);
    rendered.push_str(&diff[..boundary]);
    if !rendered.ends_with('\n') {
        rendered.push('\n');
    }
    rendered.push_str(&format!(
        "\n[workspace diff truncated at {} bytes]\n",
        MEMORY_WORKSPACE_DIFF_MAX_BYTES
    ));
}

fn previous_char_boundary(value: &str, max_bytes: usize) -> usize {
    if max_bytes >= value.len() {
        return value.len();
    }
    let mut index = max_bytes;
    while !value.is_char_boundary(index) {
        index -= 1;
    }
    index
}

fn git_stdout(root: &Path, args: &[&str]) -> Result<String, MemoryWorkspaceGitError> {
    let output = run_git(root, args)?;
    String::from_utf8(output.stdout)
        .map_err(|source| MemoryWorkspaceGitError::GitOutputUtf8 { source })
}

fn git_z_stdout(root: &Path, args: &[&str]) -> Result<Vec<u8>, MemoryWorkspaceGitError> {
    run_git(root, args).map(|output| output.stdout)
}

fn run_git(root: &Path, args: &[&str]) -> Result<std::process::Output, MemoryWorkspaceGitError> {
    let mut full_args = vec![
        "-c",
        "user.name=BitFun",
        "-c",
        "user.email=bitfun@localhost",
    ];
    full_args.extend_from_slice(args);
    run_git_raw(root, &full_args)
}

fn run_git_raw(
    root: &Path,
    args: &[&str],
) -> Result<std::process::Output, MemoryWorkspaceGitError> {
    let output = Command::new("git")
        .arg("-C")
        .arg(root)
        .args(args)
        .output()
        .map_err(|source| MemoryWorkspaceGitError::RunGit {
            root: root.to_path_buf(),
            source,
        })?;
    if output.status.success() {
        Ok(output)
    } else {
        Err(MemoryWorkspaceGitError::GitFailed {
            root: root.to_path_buf(),
            stderr: String::from_utf8_lossy(&output.stderr).to_string(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::{
        memory_workspace_diff, render_memory_workspace_diff_file,
        reset_memory_workspace_git_baseline, MemoryWorkspaceChange, MemoryWorkspaceChangeStatus,
    };

    #[tokio::test]
    async fn memory_workspace_git_diff_detects_added_modified_and_deleted_paths() {
        let temp = tempfile::tempdir().unwrap();
        let root = temp.path();
        std::fs::write(root.join("MEMORY.md"), "old index\n").unwrap();
        std::fs::write(root.join("memory_summary.md"), "old summary\n").unwrap();

        reset_memory_workspace_git_baseline(root).await.unwrap();

        std::fs::write(root.join("MEMORY.md"), "new index\n").unwrap();
        std::fs::remove_file(root.join("memory_summary.md")).unwrap();
        std::fs::create_dir_all(root.join("rollout_summaries")).unwrap();
        std::fs::write(
            root.join("rollout_summaries").join("new.md"),
            "new summary\n",
        )
        .unwrap();

        let diff = memory_workspace_diff(root).await.unwrap();

        assert!(diff.has_changes());
        assert!(diff.changes.contains(&MemoryWorkspaceChange {
            status: MemoryWorkspaceChangeStatus::Modified,
            path: "MEMORY.md".to_string(),
        }));
        assert!(diff.changes.contains(&MemoryWorkspaceChange {
            status: MemoryWorkspaceChangeStatus::Deleted,
            path: "memory_summary.md".to_string(),
        }));
        assert!(diff.changes.contains(&MemoryWorkspaceChange {
            status: MemoryWorkspaceChangeStatus::Added,
            path: "rollout_summaries/new.md".to_string(),
        }));
        assert!(diff.unified_diff.contains("new index"));
        assert!(diff.unified_diff.contains("new summary"));
    }

    #[test]
    fn memory_workspace_diff_renderer_preserves_legacy_status_header() {
        let rendered = render_memory_workspace_diff_file(&super::MemoryWorkspaceDiff {
            changes: vec![MemoryWorkspaceChange {
                status: MemoryWorkspaceChangeStatus::Added,
                path: "extensions/ad_hoc/notes/example.md".to_string(),
            }],
            unified_diff: "+note\n".to_string(),
        });

        assert!(rendered.contains("# Memory Workspace Diff"));
        assert!(rendered.contains("- A extensions/ad_hoc/notes/example.md"));
        assert!(rendered.contains("```diff\n+note\n```"));
    }
}
